/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cfp.views;
import br.com.cfp.classes.clDivida;
import br.com.cfp.classes.clExceptions;
import br.com.cfp.eventos.clBotoesDivida;

/**
 *
 * @author emerson
 */
public class CadastroDivida extends javax.swing.JInternalFrame {

    private clBotoesDivida botoes = new clBotoesDivida(this);
    private int iCodUsuario;
    
    public clDivida getDivida() throws clExceptions{
        //alimentar o objeto com informacoes do textField
        clDivida divida = new clDivida();
        String numero = txtValor.getText().replace(",", ".");
        
        verificaDados();
        
         divida.setiCod_divida(Integer.parseInt(txtCodigo.getText()));
         divida.setStrDescricao(txtDescricao.getText());
         divida.setfValor(Float.parseFloat(numero));
         divida.setStrPeriodoInicial(txtmPeriodoInicial.getText());
         divida.setStrPeriodoFinal(txtmPeriodoFinal.getText());
         divida.setiCodUsuario(iCodUsuario);
         
         if(jcbxStatus.getSelectedItem().toString().equals("Aberto"))
         {
             divida.setStrStatus("A");
         }else if(jcbxStatus.getSelectedItem().toString().equals("Baixado"))
         {
             divida.setStrStatus("B");
         }else
         {
              throw new clExceptions("Por favor, escolha um status para a divida");
         }
        
        
        return divida;
    }
    
    public clDivida limparCampos()
    {
        clDivida divida = new clDivida();
        
            txtCodigo.setText("");
            txtDescricao.setText("");
            txtValor.setText("");
            txtmPeriodoInicial.setText("");
            txtmPeriodoFinal.setText("");
            jcbxStatus.setSelectedIndex(0);
       
        return divida;
    }
    
    public clDivida apagarDivida(clDivida divida)
    {
        limparCampos();

        return null;
    }
    

    public void fecharJanela()
    {   
        
        this.dispose();   
    }
    
    /**
     * Creates new form CadastroDivida
     */
    public CadastroDivida(int iCodUsuario) {
        initComponents();
        
        btnCadastrar.addActionListener(botoes);
        btnCancelar.addActionListener(botoes);
        btnExcluir.addActionListener(botoes);
        btnLimpar.addActionListener(botoes);
        btnPesquisar.addActionListener(botoes);
        this.iCodUsuario = iCodUsuario;
    }
    
    public int getCodDivida() throws clExceptions
    {
        int cod;
        try {
            cod = Integer.parseInt(txtCodigo.getText());
            return cod;
        } catch (NumberFormatException ex) {
            throw new clExceptions("Valor de Código invalido");
        }
    }
    
    public void setDivida(clDivida divida) throws clExceptions
    {
        if(divida != null)
        {
            txtCodigo.setText(Integer.toString(divida.getiCod_divida()));
            txtDescricao.setText(divida.getStrDescricao());
            txtValor.setText(Float.toString(divida.getfValor()));
            txtmPeriodoInicial.setText(divida.getStrPeriodoInicial());
            txtmPeriodoFinal.setText(divida.getStrPeriodoFinal());
            
            switch (divida.getStrStatus()) {
                case "A":
                    jcbxStatus.setSelectedIndex(1);
                    break;
                case "B":
                    jcbxStatus.setSelectedIndex(2);
                    break;
                default:
                    jcbxStatus.setSelectedIndex(0);
                    break;
            }
            
        }else
        {
            limparCampos();
            throw new clExceptions("Divida não encontrada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1Nome9 = new javax.swing.JLabel();
        jLabel1Nome10 = new javax.swing.JLabel();
        jLabel1Nome11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtmPeriodoInicial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmPeriodoFinal = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jcbxStatus = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de Dívida");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preencha todos compos abaixo:", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel1Nome9.setText("Descrição:");

        jLabel1Nome10.setText("Valor:");

        jLabel1Nome11.setText("Periodo:");

        jLabel16.setText("Status:");

        btnCadastrar.setText("Salvar");
        btnCadastrar.setActionCommand("cadastrar");
        /*
        */

        btnExcluir.setText("Excluir");
        btnExcluir.setActionCommand("excluir");
        /*
        */

        //excluir.addActionListener(listener);

        jLabel1.setText("Codigo:");

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("cancelar");

        btnLimpar.setText("Limpar");
        btnLimpar.setActionCommand("limpar");

        try {
            txtmPeriodoInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("á");

        try {
            txtmPeriodoFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisar.setText("Pesquisar");

        jcbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Aberto", "Baixado" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1Nome10)
                            .addComponent(jLabel1Nome9)
                            .addComponent(jLabel1Nome11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtValor)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcbxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtmPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nome9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nome10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nome11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtmPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpar))
                .addGap(16, 16, 16))
        );

        btnPesquisar.setActionCommand("pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void verificaDados() throws clExceptions {

         try
         {
             Integer.parseInt(txtCodigo.getText());
         }catch(NumberFormatException ex)
         {
             throw new clExceptions("Por favor, preencha o campo de Código");
         }
         
         try
         { 
             String numero = txtValor.getText().replace(",", ".");
             Float.parseFloat(numero);
         }catch(NumberFormatException ex)
         {
             throw new clExceptions("Por favor, preencha o campo de valor obrigatório");
         }

        if (txtDescricao.getText().equals("")) {
            throw new clExceptions("Campo de Descrição Inválido");
        }

        if (txtmPeriodoInicial.getText().equals("  /  /    ")) {
            throw new clExceptions("Campo do Periodo Inicial Inválido");
        }
        
        if (txtmPeriodoFinal.getText().equals("  /  /    ")) {
            throw new clExceptions("Campo do Periodo Final Inválido");
        }

    }

    public int getiCodUsuario() {
        return iCodUsuario;
    }
     
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel1Nome10;
    private javax.swing.JLabel jLabel1Nome11;
    private javax.swing.JLabel jLabel1Nome9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbxStatus;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    private javax.swing.JFormattedTextField txtmPeriodoFinal;
    private javax.swing.JFormattedTextField txtmPeriodoInicial;
    // End of variables declaration//GEN-END:variables
}
